### ISSUE TITLE
minor: panda install bamboo should be Bamboo

### ISSUE THREAD

**Issue by CygnusAlpha** [sergot/bamboo#2]
root@a681e305f150:/home/perl6-project# panda install bamboo
resolve stage failed for bamboo: Project bamboo not found in the ecosystem. Maybe you meant Bamboo? Maybe try "panda update" first?

root@a681e305f150:/home/perl6-project# panda install Bamboo
panda provides the requested Panda
==> Fetching Bamboo
==> Building Bamboo

**Comment by sergot** [comment]
Thanks a lot!

Actually I want it to be written with the lower case 'b'. So I fixed the META.info in https://github.com/sergot/bamboo/commit/9ffb6ceceb26e8ef2799bd261500a2ee0441a88f
